### ISSUE TITLE
load pretrain 报错

### ISSUE THREAD

**Issue by MaybeOjbk** [Toyhom/Hei_Dong#1]
model = BertForSequenceClassification.from_pretrained('bert-base-chinese',num_labels=opt.num_labels)
由于在国内，好像下载不了，然后通过各种途径下载后得到了pytorch_model.bin 文件，但是 from_pretrained()时报错了
![图片](https://user-images.githubusercontent.com/38483419/76147233-20094380-60d5-11ea-8775-ed14b2f60450.png)

**Comment by MaybeOjbk** [comment]
请问怎么办啊，麻烦啦！

**Comment by Toyhom** [comment]
你这应该是编码问题，我觉得还是下载原模型比较稳妥

**Comment by MaybeOjbk** [comment]
谢谢，解决了
