### ISSUE TITLE
loss震荡

### ISSUE THREAD

**Issue by Ricardokevins** [Toyhom/Hei_Dong#2]
试了一下模型
loss一直在0-1震荡，调小学习率也没啥效果。最后的准确率75%左右
问问原环境下是这样的吗（或者是我那里做错了？）

教程和代码很不错，感谢。

**Comment by Toyhom** [comment]
bert在比较简单的任务和数据集里确实可能出现这样的情况。------------------ 原始邮件 ------------------
发件人: "kevinpro"<notifications@github.com>
发送时间: 2020年3月31日(星期二) 凌晨1:03
收件人: "Toyhom/Hei_Dong"<Hei_Dong@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Toyhom/Hei_Dong] loss震荡 (#2)




 
试了一下模型
 loss一直在0-1震荡，调小学习率也没啥效果。最后的准确率75%左右
 问问原环境下是这样的吗（或者是我那里做错了？）
 
教程和代码很不错，感谢。
 
&mdash;
